    
name: CxFlow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Checkmarx CxFlow Action
  # You may pin to the exact commit or the version.  
  # uses: checkmarx-ts/checkmarx-cxflow-github-action@fe2a395cbbee31268470d92b6c53ebc483005f0f
        uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.3
        with:
          # Provide Checkmarx URL
          checkmarx_url: https://sperasoft.checkmarx.net
          # Select a Checkmarx Team
          team: /CxServer
          # Provide Checkmarx Username #${{secrets.CHECKMARX_USERNAME}}
          checkmarx_username: ${{secrets.CHECKMARX_USERNAME}}  
          # Provide Checkmarx Password ${{secrets.CHECKMARX_PASSWORD}}
          checkmarx_password:  ${{secrets.CHECKMARX_PASSWORD}}
          # Provide Checkmarx Client Secret
          checkmarx_client_secret: 014DF517-39D1-4453-B7B3-9930C563627C
          # Select a Checkmarx Project
          project: kafdrop_action
          # Select an Application Name used by downstream bug tracker systems
          #app: # optional, default is SampleApp
          # Select a Checkmarx Preset
          #preset: # optional, default is Checkmarx Default
          # Break build based on Checkmarx findings?
          break_build: false
          # Bug tracker for the scan results.
          #bug_tracker: # optional, default is Sarif
          # Incremental Scans?
          #incremental: # optional, default is true
          # Additional CLI parameters
          #params: --cx-flow.thresholds.high=2 --cx-flow.thresholds.medium=5 --cx-flow.thresholds.low=10
          # GitHub API Token
          #github_token: # optional, default is ${{ github.token }}
          # Vulnerability Scanners (sast, sca, ast, cxgo)
          scanners: sast, sca 
          # Provide SCA API URL
          sca_api_url: https://eu.api-sca.checkmarx.net
          # Provide SCA APP URL
          sca_app_url: https://eu.sca.checkmarx.net
          # Provide SCA Access Control URL
          sca_access_control_url: https://eu.platform.checkmarx.net/
          # Provide SCA Tenant
          sca_tenant: sca_poc_tanant
          # Provide SCA Username
          sca_username: ${{secrets.SCA_USERNAME}}
          # Provide SCA Password
          sca_password: ${{secrets.SCA_PASSWORD}} 
          # Provide CxGo Client Secret
